# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('dataset', models.CharField(max_length=200)),
                ('reference_run_number', models.IntegerField()),
                ('run_number', models.IntegerField()),
                ('number_of_ls', models.IntegerField()),
                ('integrated_luminosity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pixel', models.BooleanField()),
                ('sistrip', models.BooleanField()),
                ('tracking', models.BooleanField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
