# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField()),
                ('number_of_ls', models.IntegerField()),
                ('integrated_luminosity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pixel', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=4)),
                ('sistrip', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=4)),
                ('tracking', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=4)),
                ('comment', models.TextField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certhelper.ReferenceRun')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reco', models.CharField(choices=[('Express', 'Express'), ('Prompt', 'Prompt')], max_length=30)),
                ('runtype', models.CharField(choices=[('Cosmics', 'Cosmics'), ('Collisions', 'Collisions')], max_length=30)),
                ('bfield', models.CharField(choices=[('0 Tesla', '0 Tesla'), ('3.8 Tesla', '3.8 Tesla')], max_length=30)),
                ('beamtype', models.CharField(choices=[('P-P', 'P-P'), ('Hi-P', 'Hi-P'), ('Hi-Hi', 'Hi-Hi')], max_length=30)),
                ('dataset', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together=set([('reco', 'runtype', 'bfield', 'beamtype')]),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certhelper.Type'),
        ),
    ]
