# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('reference_run', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
