# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0003_auto_20180430_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencerun',
            options={'ordering': ('-reference_run',)},
        ),
    ]
