# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0004_auto_20180514_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
