# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0007_auto_20180516_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='runinfo',
            unique_together=set([]),
        ),
    ]
