# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 15:02
from __future__ import unicode_literals

import allauth.socialaccount.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certhelper', '0008_auto_20180611_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', allauth.socialaccount.fields.JSONField(default=dict, verbose_name='extra data')),
                ('user_privilege', models.IntegerField(choices=[(0, 'Guest'), (10, 'Shifter'), (20, 'Shift Leader'), (30, 'Expert'), (50, 'Administrator')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
