# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170217_1111'),
        ('certhelper', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='problem_categories',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
