# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 15:15
from __future__ import unicode_literals

import certhelper.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0010_runinfo_problem_categories'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', certhelper.manager.SoftDeletionManager()),
                ('all_objects', certhelper.manager.SoftDeletionManager(alive_only=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='referencerun',
            managers=[
                ('objects', certhelper.manager.SoftDeletionManager()),
                ('all_objects', certhelper.manager.SoftDeletionManager(alive_only=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='runinfo',
            managers=[
                ('objects', certhelper.manager.RunInfoManager()),
                ('all_objects', certhelper.manager.RunInfoManager(alive_only=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
                ('objects', certhelper.manager.SoftDeletionManager()),
                ('all_objects', certhelper.manager.SoftDeletionManager(alive_only=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='subsubcategory',
            managers=[
                ('objects', certhelper.manager.SoftDeletionManager()),
                ('all_objects', certhelper.manager.SoftDeletionManager(alive_only=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='type',
            managers=[
                ('objects', certhelper.manager.SoftDeletionManager()),
                ('all_objects', certhelper.manager.SoftDeletionManager(alive_only=False)),
            ],
        ),
    ]
