# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0012_migrate_old_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(help_text='Text that will be displayed at the bullet point', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Text that will be displayed as a tooltip over the bullet point')),
                ('modal_name', models.CharField(blank=True, help_text="Name of the HTML modal to open within the page on click. e.g. if modal id is 'modal-trackermap-id' then enter just 'trackermap' ", max_length=15, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certhelper.Checklist')),
            ],
        ),
    ]
