# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 12:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0012_migrate_old_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Text that will be displayed above the checklist items to provide further information needed to the explain the problems')),
                ('additional_description', ckeditor.fields.RichTextField(blank=True, help_text='Text that will be displayed under the checklist items to provide tips and links')),
                ('identifier', models.SlugField(help_text='Short unique word used to identify the checklist in the website. Examples: general, trackermap, pixel, sistrip, tracking', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(help_text='Text that will be displayed at the bullet point')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Used as a Subheadline to group bullet points together', max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Text that will be displayed above the checklist items to providefurther information needed to the explain the problems')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certhelper.Checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklistgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certhelper.ChecklistItemGroup'),
        ),
    ]
