# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0013_checklist_checklistitem_checklistitemgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('runtype', 'reco', '-id')},
        ),
    ]
