# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0015_referencerun_type_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='pixel_lowstat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='sistrip_lowstat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='tracking_lowstat',
            field=models.BooleanField(default=False),
        ),
    ]
