# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0016_runinfo_lowstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencerun',
            name='beamenergy',
            field=models.CharField(choices=[('Cosmics', 'Cosmics'), ('5 TeV', '5 TeV'), ('6.4 TeV', '6.4 TeV'), ('13 TeV', '13 TeV')], max_length=10),
        ),
        migrations.AlterField(
            model_name='type',
            name='beamenergy',
            field=models.CharField(choices=[('Cosmics', 'Cosmics'), ('5 TeV', '5 TeV'), ('6.4 TeV', '6.4 TeV'), ('13 TeV', '13 TeV')], max_length=10),
        ),
    ]
