# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0017_auto_20181111_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='int_luminosity',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
