# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certhelper', '0018_auto_20181112_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='runinfo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='runinfo',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='runinfo',
            name='subsubcategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='SubSubCategory',
        ),
    ]
